import Head from 'next/head'
import { Magic } from 'magic-sdk'
import Web3 from 'web3'
import { useEffect } from 'react'

export default function Home() {
  let magic;

  useEffect(() => {
    magic = new Magic('PUBLISHABLE_KEY_HERE', {
      network: "goerli",
    })
  }, [])

  const connectMagic = async () => {
    const web3 = new Web3(magic.rpcProvider)
    const accounts = await magic.wallet.connectWithUI()
  };

  const showWalletUi = async () => {
    const walletInfo = await magic.wallet.getInfo();
    const walletType = walletInfo.walletType;

    if (walletType === "magic") {
      await magic.wallet.showUI();
    };
  }

  return (
    <>
      <Head>
        <title>Magic.link proof-of-concept</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{display: 'flex', width: '100%', height: '100vh', alignContent: 'center', justifyContent: 'center'}}>
        <button onClick={connectMagic} style={{alignSelf: 'center'}}>Connect Magic</button> &nbsp; 
        <button onClick={showWalletUi} style={{alignSelf: 'center'}}>Show Magic wallet UI</button>
      </div>
    </>
  )
}
